GameON/Controllers/CreditCardController.cs
using GameON.Persistence;
using GameON.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameON.Core.Models;

namespace GameON.Controllers
{

    [Authorize]
    public class CreditCardController : Controller
    {
        private readonly UnitOfWork _unitOfWork;
        public CreditCardController()
        {
            _unitOfWork = new UnitOfWork(new ApplicationDbContext());
        }
        
        public ActionResult SubscribeUser()
        {
            var userId = User.Identity.GetUserId();
            var creditCard = _unitOfWork.CreditCards.GetCreditCard(userId);
            creditCard.PaySubsciption(50);
            _unitOfWork.Complete();
            return RedirectToAction("Index", "Home");
        }

        // GET: CreditCard
        public ActionResult Subscribe()
        {
            var userId = User.Identity.GetUserId();
            var creditCard = _unitOfWork.CreditCards.GetCreditCard(userId);
            if (creditCard.User is null)
            return RedirectToAction("Index", "Home");
            return View(creditCard);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreditCardFormViewModel viewModel)
        {
            var userId = User.Identity.GetUserId();

            var creditCard = new CreditCard(userId, viewModel.CardNumber, viewModel.GetDateTime(), viewModel.CCV);

            _unitOfWork.CreditCards.Add(creditCard);
            _unitOfWork.Complete();

            return View("Subscribe", creditCard);
        }
    }
}

GameON/Views/CreditCard/CreditCardForm.cshtml
@model GameON.ViewModels.CreditCardFormViewModel
@{
    ViewBag.Title = "Add Card";
}

<h2>Add a Card</h2>

@using (Html.BeginForm("Create", "CreditCard"))
{
    <p class="alert alert-info">All Fields are <strong>required</strong></p>
    @Html.AntiForgeryToken()
    @Html.HiddenFor(c => c.UserId)
    <div class="form-group">
        @Html.LabelFor(c=> c.CardNumber)
        @Html.TextBoxFor(c => c.CardNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.CardNumber)
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.ExpireDate)
        @Html.TextBoxFor(c => c.ExpireDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.ExpireDate)
    </div>

    <div class="form-group">
        @Html.LabelFor(c => c.CCV)
        @Html.TextBoxFor(c => c.CCV, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.CCV)
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>


}
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

GameON/Views/CreditCard/Subscribe.cshtml
@model GameON.Core.Models.CreditCard
@{
    ViewBag.Title = "Subscribe";
}

<h2>Subscribe</h2>



@if (Model.User.IsSubscribed)
{
    <p class="alert alert-info">You already have a Subscription</p>
}
else
{
    <ul>
        <li>mpla mpla</li>
        <li>mpla mpla</li>
        <li>mpla mpla</li>
        <li>mpla mpla</li>
    </ul>
    <p>Subscription fee: 50 EUR</p>
    <p>@Html.ActionLink("Subscribe", "SubscribeUser", "CreditCard")</p>
}